### ISSUE TITLE
Unknown Module Error  

### ISSUE THREAD

**Issue by mrmoyeez** [markshust/magento2-module-twilio#1]
Hello Sir i am getting issue when i trying to enabled your extension on my magento 2.2.6 store. It showed me unknown module. Can you help me on this why its showing unknown module. Thanks

![un](https://user-images.githubusercontent.com/8894125/67550803-cf460f00-f720-11e9-8681-7bf955ac2247.PNG)

**Comment by markshust** [comment]
hi there, do you have the module code installed? you will need to run `composer require markshust/magento2-module-twilio` first before enabling.
